BlogTask/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
get 'signup'  => 'users#new'

  resources :post_attachments

  resources :posts
  resources :categories
  resources :comments
  resources :replys
  resources :users do
    member do
      post :edit_display_picture
	    post :add_info
      post :change_signature
      post :change_info
      post :change_name
      post :request_auth
    end
  end

  get '/admin/show_requests', to: 'admins#show_requests'
  get '/admin/accept_request', to: 'admins#accept_request'
  get '/admin/reject_request', to: 'admins#reject_request'
  get '/user/edit_info', to:'users#edit_info'
  get '/Profiles/NadineProfile' , to:'profiles#NadineProfile'
 get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
 get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'

  get '/Profiles/BadrProfile' , to:'profiles#BadrProfile'
  get '/Profiles/MeloukProfile' , to:'profiles#MeloukProfile'
  get '/Profiles/OufaProfile' , to:'profiles#OufaProfile'
  get '/Profiles/AliProfile' , to:'profiles#AliProfile'
  get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
  get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'
  get '/Profiles/MarwaProfile' , to:'profiles#MarwaProfile'
  get '/Profiles/AnasProfile', to: 'profiles#AnasProfile'
  get '/homepages/home' , to:'homepages#home'
  get '/admins/login', to: 'admins#login'
  post '/admins/login', to:'admins#signin'
  resources :admins do
    collection do
      get 'authenticated_users'
      get'unauthenticated_users'
      get 'show_requests'
    end
  end

  root 'homepages#home'

end

BlogTask/app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
	mount_uploader :avatar, AvatarUploader
    belongs_to :post
end

BlogTask/app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment.post, notice: 'Post attachment was successfully updated.' }
      end 
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :avatar)
    end
end

BlogTask/app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

BlogTask/app/views/post_attachments/_form.html.erb
<%= image_tag @post_attachment.avatar %>
<%= form_for(@post_attachment) do |f| %>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

BlogTask/app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

BlogTask/app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.avatar %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post attachment', new_post_attachment_path %>

BlogTask/app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', post_attachments_path %>

BlogTask/app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post_attachment.post_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>