BlogTask/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
get 'signup'  => 'users#new'

  resources :post_attachments

  resources :posts
  resources :categories
  resources :comments
  resources :replys
  resources :users do
    member do
      post :edit_display_picture
	    post :add_info
      post :change_signature
      post :change_info
      post :change_name
      post :request_auth
    end
  end

  get '/admin/show_requests', to: 'admins#show_requests'
  get '/admin/accept_request', to: 'admins#accept_request'
  get '/admin/reject_request', to: 'admins#reject_request'
  get '/user/edit_info', to:'users#edit_info'
  get '/Profiles/NadineProfile' , to:'profiles#NadineProfile'
 get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
 get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'

  get '/Profiles/BadrProfile' , to:'profiles#BadrProfile'
  get '/Profiles/MeloukProfile' , to:'profiles#MeloukProfile'
  get '/Profiles/OufaProfile' , to:'profiles#OufaProfile'
  get '/Profiles/AliProfile' , to:'profiles#AliProfile'
  get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
  get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'
  get '/Profiles/MarwaProfile' , to:'profiles#MarwaProfile'
  get '/Profiles/AnasProfile', to: 'profiles#AnasProfile'
  get '/homepages/home' , to:'homepages#home'
  get '/admins/login', to: 'admins#login'
  post '/admins/login', to:'admins#signin'
  resources :admins do
    collection do
      get 'authenticated_users'
      get'unauthenticated_users'
      get 'show_requests'
    end
  end

  root 'homepages#home'

end

BlogTask/app/views/admins/authenticated_users.html.erb
<ul>
	<% @authenticated_users.each do |user| %>
		<li>
			<%= link_to user.email, user_path(user) %> 
		</li>
	<% end %>
</ul>

BlogTask/app/views/admins/login.html.erb

<div></div>
<%= form_for :admins, method: :signin do |f| %>
	<strong><%= f.label :"Admin Login" %></strong>
	
	<br>
	
	<strong><%= f.label :"Password:" %></strong>
	<%= f.password_field :pass %>
	<%= f.submit "Login" %>
	<% end %>

BlogTask/app/views/admins/show.html.erb
<link rel="stylesheet" type="text/css" href="admins.css" />
	<title></title>

	<div id="main">
			<div id="unauthe">
				<strong><%= "view unauthenticated users " %> </strong>
					<div id="unAuthUsers">
						<ul>
							<% @unauthenticated_users.each do |user| %>
								<li>
								<%=  user.email %> 
								</li>
							<% end %>
						</ul>

			</div>
	</div>

	<div id="authe">
		<strong><%= "view authenticated users " %></strong>
			<div id="authUser">
				<ul>
						<% @authenticated_users.each do |user| %>
							<li>
								<%=  user.email %> 
							</li>
						<% end %>
				</ul>
			</div>
	</div>

	<div id="autheRequests">	
		<strong><%=  "View requests" %></strong>
			<div id="req">
				<br>

				<% if @request_users %>
					<% @request_users.each do |request| %>
							<%= request. email %>
							<br>
							<!-- then add links to cancel and button to reject -->
							<%= link_to 'accept', admin_accept_request_path(user_request: request.id) %>
							|
							<%= link_to 'reject', admin_reject_request_path(user_request: request.id) %>
							<br>
							<br>
						
					<% end %>
				<% else %>
				<%= "No requests to show" %>
				<% end %>				
			</div>
	</div>

</div>

BlogTask/app/views/admins/show_requests.html.erb
<br>
<br>
<br>

<% if @request_users %>
	<% @request_users.each do |request| %>
			<%= request. email %>
			<br>
			<%= "" %>
			<br>
			<!-- then add links to cancel and button to reject -->
			<%= link_to 'accept', admin_accept_request_path(user_request: request.id) %>
			|
			<%= link_to 'reject', admin_reject_request_path(user_request: request.id) %>
			<br>
		
	<% end %>
<% else %>
<%= "No requests to show" %>
<% end %>

BlogTask/app/views/admins/unauthenticated_users.html.erb
<ul>
	<% @unauthenticated_users.each do |user| %>
		<li>
			<%= link_to user.email, user_path(user) %> 
		</li>
	<% end %>
</ul>