BlogTask/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
get 'signup'  => 'users#new'

  resources :post_attachments

  resources :posts
  resources :categories
  resources :comments
  resources :replys
  resources :users do
    member do
      post :edit_display_picture
	    post :add_info
      post :change_signature
      post :change_info
      post :change_name
      post :request_auth
    end
  end

  get '/admin/show_requests', to: 'admins#show_requests'
  get '/admin/accept_request', to: 'admins#accept_request'
  get '/admin/reject_request', to: 'admins#reject_request'
  get '/user/edit_info', to:'users#edit_info'
  get '/Profiles/NadineProfile' , to:'profiles#NadineProfile'
 get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
 get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'

  get '/Profiles/BadrProfile' , to:'profiles#BadrProfile'
  get '/Profiles/MeloukProfile' , to:'profiles#MeloukProfile'
  get '/Profiles/OufaProfile' , to:'profiles#OufaProfile'
  get '/Profiles/AliProfile' , to:'profiles#AliProfile'
  get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
  get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'
  get '/Profiles/MarwaProfile' , to:'profiles#MarwaProfile'
  get '/Profiles/AnasProfile', to: 'profiles#AnasProfile'
  get '/homepages/home' , to:'homepages#home'
  get '/admins/login', to: 'admins#login'
  post '/admins/login', to:'admins#signin'
  resources :admins do
    collection do
      get 'authenticated_users'
      get'unauthenticated_users'
      get 'show_requests'
    end
  end

  root 'homepages#home'

end

BlogTask/app/models/post.rb
class Post < ActiveRecord::Base
	#edited_by_mariam
	has_many :mediavideos
	belongs_to :user, dependent: :destroy
	#edited_by_mariam
	#has_many :categories
	has_many :categoryofposts
	has_many :categories, through: :categoryofposts
	has_many :post_attachments
   	accepts_nested_attributes_for :post_attachments
	#has_many :related_categories, class_name: "Category", through: :categoryofposts , source: :category
	#end
	has_many :comments

	validates :body, length: {
    minimum: 1,
    maximum: 400
	}
	validates :title, length: {
    minimum: 1,
    maximum: 60
	}
end

BlogTask/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	#to be added later : mariam
	#before_action :authenticate_user!, except: [:index]
	#before_action :authenticated_user!, only: [:new, :create]
	#end mariam

	def index
		@post = Post.new
		if params["search"]
			@search_tags = params["search"]
			@tags = @search_tags.split(',')
			@posts_array = []
			@posts_ids = []
			@tags.each do |tag|
				@category = Category.find_by(name: tag)
				if @category
					@temp_posts = @category.related_posts
					if @temp_posts
						@temp_posts.each do |p|
							unless @posts_ids.include?(p[:id])
								@posts_array << p
								@posts_ids << p[:id]
							end
						end  
					end
				end
			end
			@posts = @posts_array
		else
			@posts = Post.all.order(created_at: :desc)
		end
	end

	def new
		@post = Post.new
		@post_attachment = @post.post_attachments.build
	end

	def create
		if current_user and current_user.auth
			@post_params = post_params
			if !(current_user.signature).nil?
				@post_params[:body] = @post_params[:body] + " " + current_user.signature
			end
			@post_params[:user_id] = current_user.id
			@related_categories = params[:search]
			if @related_categories
				@all_categories = @related_categories.split(',')
			end
			@categories = []
			@categories_ids = []
			if @all_categories
				@all_categories.each do |c|
					@temp_category = Category.find_by(name: c)
					if @temp_category 
						unless @categories_ids.include?(@temp_category.id)
							@categories_ids << @temp_category.id
							@categories << @temp_category
						end
					else
						@new_category = Category.new
						@new_category.name = c
						@new_category.save
						@categories_ids << @new_category.id
						@categories << @new_category
					end
				end
			end

			@post_txt = post_params[:body]
			@www_index = @post_txt.index("www.youtube.com/watch?v=")
			@video_ids = []
			if @www_index
				while @www_index > -1 do	
					if @post_txt
						@video_id = @post_txt[@www_index + 24, 11]
					end
					@cut = @www_index + 24 + 11
					if @post_txt
					@total_len = @post_txt.length
					else 
						@total_len = 0
					end
					if @post_txt
						@post_txt = @post_txt[@www_index + 24 + 11, @total_len - @cut -1]
						@video_ids << @video_id
						if @post_txt
							@www_index = @post_txt.index("www.youtube.com/watch?v=")
						else
							@www_index = -1
						end
					end
					unless @www_index
						@www_index = -1
					end
				end
			end



			@post_params[:categories] = @categories
			@post = Post.new(@post_params)
			respond_to do |format|
				if @post.save
					if @video_ids
						@video_ids.each do |v|
							@temp_video = Mediavideo.new
							@temp_video.youtube_id = v
							@temp_video.post_id = @post.id
							@temp_video.save
						end
					end
					if (params[:post_attachments])
						params[:post_attachments]['avatar'].each do |a|
			            	@post_attachment = @post.post_attachments.create!(:avatar => a, :post_id => @post.id)
			        	end
		        	end
					format.html { redirect_to user_path(current_user), notice: "The post has been posted successfully."}
					format.js
				else
					#render action: :new, alert: "The post has not been posted."
					format.html { redirect_to user_path(current_user) }
				end
			end
		else
			flash[:error] = "Something went wrong!"
		end	
	end

	def edit
	end

	def update
	end

	def destroy
	end

	def show
		@post = Post.find(params[:id])
		#@posted_by = User.find(@post.user_id)
		@comments = Comment.where(post_id: @post.id)
	end


  protected
	def post_params
		params.require(:post).permit(:title, :body, post_attachments_attributes: [:id, :post_id, :avatar])
	end
end

BlogTask/app/helpers/posts_helper.rb
module PostsHelper
end

BlogTask/app/views/posts/_form.html.erb
<%= form_for @post, :html => { :multipart => true }, remote: true do |p| %>

	<% if @post.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved:</h2>

	      <ul>
	      <% @post.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>

	<%= p.label :title %>
	<%= p.text_field :title %>
	<br>
	<%= p.label :body %>
	<%= p.text_area :body %>
	<br>
	<p>Related to : </p>
	<br>
	<%= text_field_tag 'search', nil, placeholder: 'Enter related tags separated by commas.' %>
	<br>
	<%= p.fields_for :post_attachments do |f| %>
       <%= f.label :avatar %><br>
       <%= f.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
   <% end %>
	<br>
	<%= p.submit "Create" %>
<% end %>

BlogTask/app/views/posts/_post.html.erb
<h4><strong><%= post.title %></strong> </h4>
<h6><em><%= post.created_at %></em></h6>
<p> <%= post.body%> </p></br>
<% @categories = @post.categories %>
		<% if @categories and @categories.length > 0 %>
			<p><%= "Related to:" %></p>
		
			<% @categories.each do |category| %>
				<%= link_to category[:name] , category_path(category[:id]) %>
			<% end %>
		<% end %>
		</br>
<% @att = post.post_attachments.all %>
		<% if @att and @att.length > 0%>
			<p><%= "Attachments" %></p>
			<% @att.each do |p| %>
				<div id="attach">
	  			<%= image_tag p.avatar_url %>
	  			</div>
	  			</br>
	  	<% end %>
<% end %>

</br>

<% @p = "http://127.0.0.1:3000/posts/" + (post.id).to_s %>
<%= link_to "view post" , @p %>
<div id="empty">
	</br>
	</br>
</div>

BlogTask/app/views/posts/create.js.erb
$('#post').prepend("<%= j render @post %>")

BlogTask/app/views/posts/index.html.erb
<div></div>
<br>
<br>
<br>
 
<div id="newPost">
<%= form_for @post, :html => { :multipart => true }, remote: true do |p| %>

		<% if @post.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved:</h2>

		      <ul>
		      <% @post.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
	  	<% end %>

		<%= p.label :title %>
		<%= p.text_field :title %>
		<br>
		<%= p.label :body %>
		<%= p.text_area :body %>
		<br>
		<p>Related to : </p>
		<br>
		<%= text_field_tag 'search', nil, placeholder: 'Enter related tags separated by commas.' %>
		<br>
		<%= p.fields_for :post_attachments do |f| %>
	       <%= f.label :avatar %><br>
	       <%= f.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
  	 	<% end %>
		<br>
		<div style="width: 100px; text-align: center">
		<%= p.submit "Create" %>
		</div>
	<% end %>
</div>
</br>
</br>
<div id="search">
	<%= form_tag('/posts', method: :get) do %>
		Tags:
		<br>
		<%= text_field_tag 'search', nil, placeholder: 'Enter search tags...' %>
			<div style="width: 100px; text-align: center"><%= submit_tag 'Search' %></div>
		<% end %>
</div>
</br>
</br>

<div id="allposts">
	<% @posts.each do |post| %>
	<div id="singlePost">
		<% @post = Post.find(post[:id]) %>
		<% @u = User.find(@post[:user_id]) %>
		
			<h2><strong><%= link_to post[:title], post_path(post[:id]) %></strong></h2>
			</br>
			
			
			<h5><strong>Posted by:</strong> </br>
			<%= link_to @u.email, user_path(@u) %>
			</h5>
			
			<br>

			<h5><%= post.created_at %></h5>
			
			<h3><%= post[:body] %></h3>

			<% @att = @post.post_attachments.all %>
			<% if @att and @att.length > 0 %>
				<h6><%= "Attachments" %></h6>
				<% @att.each do |p| %>
		  			<div id="attach1">
		  			<%= image_tag p.avatar_url %>
		  			</div>
		  			<br>
				<% end %>
			<% end %>
			<br>
			<% @categories = @post.categories %>
			<% if @categories and @categories.length > 0 %>
				<%= "Related to:" %>
				<% @categories.each do |category| %>
					<%= link_to category[:name] , category_path(category[:id]) %>
				<% end %>
			<% end %>
	</div>
	<br>
	<% end %>
	</div>
	<br>
	<br>
	<br>

BlogTask/app/views/posts/new.html.erb
<%= form_for @post, :html => { :multipart => true } do |p| %>

	<% if @post.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved:</h2>

	      <ul>
	      <% @post.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>

	<%= p.label :title %>
	<%= p.text_field :title %>
	<br>
	<%= p.label :body %>
	<%= p.text_area :body %>
	<br>
	<p>Related to : </p>
	<br>
	<%= text_field_tag 'search', nil, placeholder: 'Enter related tags separated by commas.' %>
	<br>
	<%= p.fields_for :post_attachments do |f| %>
       <%= f.label :avatar %><br>
       <%= f.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
   <% end %>
	<br>
	<%= p.submit "Create" %>
<% end %>

BlogTask/app/views/posts/new.js.erb
$('#new_link').hide().after('<%= j render "form" %>');

BlogTask/app/views/posts/show.html.erb
<div></div>
<br/><br/><br/>



<div class="viewP">
	<% @user = User.find(@post.user_id) %>
	<h5>Posted by: </h5><h2><%= link_to @user.email, user_path(@user) %></h2>
	<h6><%= @post.created_at %></h6></br>
	<h5>Title:  </h5><h3><%= @post.title %></h3></br>
	<h5>Body: </h5><h4><%= @post.body %></h4><br>
	<% @l = "http://127.0.0.1:3000/posts/" + (@post.id).to_s %>
	<%= social_share_button_tag("Share this post", :url => @l) %>
	<% @categories = @post.categories %>
	<% if @categories and @categories.length > 0 %>
		<h5><%= "Categories: " %>
		<% @categories.each do |c|%>
			<%= link_to c.name, category_path(c.id) %>
		<% end %></h5>
	<% end %>
	<br>
	<% @attachments = @post.post_attachments.all %>
	<% if @attachments and @attachments.length > 0 %>
		<% @attachments.each do |a| %>
			<div id="attach7">
				<%= image_tag a.avatar_url %>
			</div>
			</br>
		<% end %>
	<% end %>
</div>

</br>

<div class="postAComment">
	<h3>Post a comment</h3>
	<% @comment = Comment.new %>
	<%= form_for @comment , :url => comments_path(post_id: @post.id)  do |c| %>
			<%= c.text_field :body %>
				<br>
			<%= c.submit 'comment' %>
		<% end %>
</div>

</br>

<div class="PostComments">
	<% @comments = @post.comments %>
	<% if @comments and @comments.length > 0 %>
		<h3><%= "Comments" %></h3>
		<% @comments.each do |c|%>
			<div class="OneComment">
				<% @user = User.find(c.user_id) %>
				<h4><%= link_to @user.email+":", @user %></h4>
				<h5><%= c.body %></h5>
				<br>
					<div class="Replies">
						<% @replies = Reply.where(comment_id: c.id) %>
						<% if @replies and @replies.length > 0 %>
							<h4><%= "Replies" %></h4>
							<% @replies.each do |reply| %>
								<% @reply_user =  User.find(reply.user_id) %>
								<h5><%= link_to @reply_user.email+":", user_path(@reply_user.id) %></h5>
								<h6><%= reply.body %></h6>
							<% end %>
						<% end %>
					</div> 
					<br>
					<div id="">
						<h4>Post a reply</h4>
						<% @reply = Reply.new %>
						<%= form_for @reply , :url => replys_path(comment_id: c.id)  do |c| %>
							<%= c.text_field :body %>
							<%= c.submit 'reply' %>
						 <% end %>
					</div>
			</div>
			<br>
		<% end %>
	<% end %>
</div>
<br>


	
		
		
		

		
	      

	      


		

		