BlogTask/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
get 'signup'  => 'users#new'

  resources :post_attachments

  resources :posts
  resources :categories
  resources :comments
  resources :replys
  resources :users do
    member do
      post :edit_display_picture
	    post :add_info
      post :change_signature
      post :change_info
      post :change_name
      post :request_auth
    end
  end

  get '/admin/show_requests', to: 'admins#show_requests'
  get '/admin/accept_request', to: 'admins#accept_request'
  get '/admin/reject_request', to: 'admins#reject_request'
  get '/user/edit_info', to:'users#edit_info'
  get '/Profiles/NadineProfile' , to:'profiles#NadineProfile'
 get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
 get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'

  get '/Profiles/BadrProfile' , to:'profiles#BadrProfile'
  get '/Profiles/MeloukProfile' , to:'profiles#MeloukProfile'
  get '/Profiles/OufaProfile' , to:'profiles#OufaProfile'
  get '/Profiles/AliProfile' , to:'profiles#AliProfile'
  get '/Profiles/SohaProfile' , to:'profiles#SohaProfile'
  get '/Profiles/MariamProfile' , to:'profiles#MariamProfile'
  get '/Profiles/MarwaProfile' , to:'profiles#MarwaProfile'
  get '/Profiles/AnasProfile', to: 'profiles#AnasProfile'
  get '/homepages/home' , to:'homepages#home'
  get '/admins/login', to: 'admins#login'
  post '/admins/login', to:'admins#signin'
  resources :admins do
    collection do
      get 'authenticated_users'
      get'unauthenticated_users'
      get 'show_requests'
    end
  end

  root 'homepages#home'

end

BlogTask/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :posts
	has_many :comments
	has_many :replies
	#validates_uniqueness_of :username
	validates :information, length: {
    maximum: 240
	}
	validates :signature, length: {
    maximum: 30
	}
	scope :authenticated, -> {
	where(auth: true)
	}
	scope :unauthenticated, -> {
		where(auth:false)
	}
	 mount_uploader :profileImage, ImageUploader
end

BlogTask/app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def change_name
		User.update(current_user.id, name: params[:n])
		redirect_to user_path(current_user)
	end

	def request_auth
		User.update(current_user.id, request: true)
		redirect_to user_path(current_user)
	end

	def add_info
		@user = current_user
	end	

	def change_signature
		User.update(current_user.id, signature: params[:sig])
		redirect_to user_path(current_user)
	end

	def change_info
		User.update(current_user.id, information: params[:info])
		redirect_to user_path(current_user)
	end

	def edit_info
		@user = current_user
	end


	def edit_display_picture
		@user = current_user
		if params[:image].present?
			@user.profileImage = params[:image]
		elsif params[:image_url].present?
			@user.remote_profileImage_url = params[:image_url]
		else 
			flash[:error] = " No image uploaded "
			redirect_to :back
			return
		end

		if @user.save
			flash[:notice] = "Successfully changed profile picture."
			redirect_to @user
		else 
			flash[:error] = "Something went wrong!"
			puts "***********"
			redirect_to :back
		end 	
	end

	def index
	end

	def show
		@user = User.find(params[:id])
		@post = Post.new
		@posts = Post.where(user_id: @user.id).order(created_at: :desc)
		@post_attachment = @post.post_attachments.build
	end

	def new
		 @user = User.new
    end

    def create
    @user = User.new(user_params)    # Not the final implementation!
   	if @user.save
   		flash[:success] = "Welcome to the Game!"
    		redirect_to @user
    else
      render 'new'
    end
	end
	
	private
	def user_params
      params.require(:user).permit(:username, :name, :password)
  	end

 end

BlogTask/app/helpers/users_helper.rb
module UsersHelper
	
end

BlogTask/app/views/users/add_info.html.erb
<p> oibxwu </p>

BlogTask/app/views/users/edit_info.html.erb
<div>
</div>
<br>
<br>
<br>
</br>
<div>
<%= form_tag change_name_user_path @user , method: :change_name do %>
<p>
	<%= "Add/change name:" %>
	<%= text_field_tag :n %>
</p>
<p>
<%= submit_tag "Apply changes"%>
</p>
<% end %>
</div>
</br>
<div>
<%= form_tag change_signature_user_path @user , method: :change_signature do %>
<p>
	<%= "Add/change signature" %>
	<%= text_field_tag :sig %>
</p>
<p>
<%= submit_tag "Add/change signature"%>
</p>
<% end %>
</div>
</br>
<div>
<%= form_tag change_info_user_path @user , method: :change_info do %>
<p>
	<%= "Add/Change Information" %>
	<%= text_field_tag :info %>
</p>

<p>
	<%= submit_tag "add/change info" %>
</p>
<% end %>
</div>
</br>
<div>
<%= "Change display picture" %>
<%= form_tag edit_display_picture_user_path(@user) , :multipart => true, method: :post do %>
		<%= "image url" %>
		<%= text_field_tag :image_url %><br />

		<%= file_field_tag :image %> 

		<%= submit_tag %>
	<% end %>
</div>

BlogTask/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

BlogTask/app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" type="text/css" href="show.css" />
	<title></title>
</head>
<body>
<div id="userProf">
<div id="bar1" >

</div>
<br>
<br>
<div id="basic">

	<div id="profileImage">
		<%= image_tag(@user.profileImage) %>
	</div>

	<div id="share">
		<% @l = "http://127.0.0.1:3000/users/" + (@user.id).to_s %>
		<%= social_share_button_tag("Share this profile", :url => @l) %>
		<br>
		<% if @user.auth %>
			<%= image_tag "http://i.imgur.com/Fu963fR.png" %>
		<% end %>
		<br>
		<div style="width: 100%">
		<% if @user == current_user and !current_user.auth and !current_user.request %>
			<%= button_to "Request auth", {:controller => :users, :action => :request_auth} %>
		<% end %>
		<br>
		</div>
	</div>


	<div id="userInfo">
		<div id="content">
		<strong>Name:</strong>
		</br> 
		<%=@user.name %></br>
		</br>
		<strong>Email:</strong>
		</br> 
		<%=@user.email %></br>
		</br><br>
		<strong>Info:</strong></br>
		<%= @user.information %></br>
		<br>
		<br>
		<% if @user.id = current_user.id %>
		</div>
			<div id="edit">
				<%= link_to "Edit your information" , '/user/edit_info' %>
			</div>
		<% end -%>
	</div>

	<div id="userPosts">
		<div id="post">
			<%= render @posts %>			
		</div>
	</div>

	<div id="addPost">
	<%= form_for @post, :html => { :multipart => true }, remote: true do |p| %>

	<% if @post.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this category from being saved:</h2>

	      <ul>
	      <% @post.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>

	<%= p.label :title %>
	<%= p.text_field :title %>
	<br>
	<%= p.label :body %>
	<%= p.text_area :body %>
	<br>
	<p>Related to : </p>
	<br>
	<%= text_field_tag 'search', nil, placeholder: 'Enter related tags separated by commas.' %>
	<br>
	<%= p.fields_for :post_attachments do |f| %>
       <%= f.label :avatar %><br>
       <%= f.file_field :avatar, :multiple => true, name: "post_attachments[avatar][]" %>
   <% end %>
	<br>
	<%= p.submit "Create" %>
<% end %>
	</div>
	
</div>
<br>
<br>
<br>
<br>

</div>
</body>
</html>